name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn lint
    - name: Run tests-setup
      run: |
              docker run -d -p 6379:6379 redis:alpine
              cp config/codes.yaml{.sample,}
              cp .env{.sample,}
    - run: yarn test
